// AUTH
export const LOGIN = 'LOGIN'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'

// DATABASE
export const SELECTED_DIRECTORY = 'SELECTED_DIRECTORY'
export const SELECTED_FILE = 'SELECTED_FILE'
export const OPEN_DIRECTORY_SELECTOR = 'OPEN_DIRECTORY_SELECTOR'
export const OPEN_FILE_SELECTOR = 'OPEN_FILE_SELECTOR'
